name: Build APK

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Build Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libncurses5:i386 \
            libstdc++6:i386 \
            python3 \
            python3-pip
          pip3 install --upgrade Cython==0.29.19

      - name: Set Up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4  # Replace with your Python version

      - name: Install Buildozer
        run: pip install --upgrade buildozer

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Build APK
        run: buildozer android debug

  artifacts:
    paths:
      - ./bin/*.apk
